### ISSUE TITLE
Add a poetry.lock/requirements.txt file for each mesh

### ISSUE THREAD

**Issue by pmav99** [seareport/seareport_meshes#6]
As it is there are no lock files whatsoever. Furthermore with the current structure whenever we update one of the dependencies, the scripts might generate a different mesh. This is definitely not what we want. Each mesh version should have its own lock file.

**Comment by tomsail** [comment]
Is this enough to reproduce the environment ? 
```
cd v0
mamba env create -n v0 -f binary-om-telemac-openmpi-p3.11.lock
python -mvenv .venv
source .venv/bin/activate
poetry install
```
If it is, I will update README
