### ISSUE TITLE
v2.1 is missing

### ISSUE THREAD

**Issue by pmav99** [seareport/seareport_meshes#7]

**Comment by tomsail** [comment]
`v2.1` is in reality `v2.2`. 

More context on this, we called: 
- `v2.0` the first mesh generated with pyposeidon with L5 GSHHS coastlines 
- `v2.1`, the same `v2.0` mesh with new bathy assignation. 
- `v2.2` the mesh generated with this replicable git with L6 GSHHS coastlines 

Only `v2.2` is replicable. 
I refactored the script that generates it and the folder to `v2.2`.

**Comment by pmav99** [comment]
great
